### ISSUE TITLE
clean up roadmap

### ISSUE THREAD

**Issue by Remi-Gau** [incf-nidash/nidmresults#62]
- [x] move testing to GHA
- [x] update to avoid any failing or flaky test
- [x] update packaging (setup.py + setuptools -> pyproject.toml + hatchling)
- [x] use pytest for testing and get coverage
- [x] enforce code style: black + flake8 + precommit
- [x] upgrade code to use more modern python features: https://github.com/asottile/pyupgrade
- [x] incorporate refactoring from sourcery: https://github.com/Remi-Gau/nidmresults/pull/1
